### ISSUE TITLE
Support Firefox for Android

### ISSUE THREAD

**Issue by jtojnar** [psimonyi/show-titletext#1]
Just checking which APIs are missing:

- [ ] [contextMenus](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/menus#Browser_compatibility).{create,onClicked,removeAll} ([bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1269062))
- [x] [runtime.onMessage](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime#Browser_compatibility)
- [x] [storage.onChanged](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage#Browser_compatibility)
- [ ] [storage.sync](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/sync#Browser_compatibility)
- [x] [tabs.executeScript](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/executeScript#Browser_compatibility)
- [x] [tabs.insertCSS](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/insertCSS#Browser_compatibility)
- [x] [tabs.sendMessage](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/sendMessage#Browser_compatibility)
- [x] [webNavigation.onDOMContentLoaded](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webNavigation/onDOMContentLoaded#Browser_compatibility)

**Comment by psimonyi** [comment]
More generally, we just need *some* sort of non-terrible interface for defining rules.  It doesn't necessarily have to be context menus.

**Comment by psimonyi** [comment]
Firefox for Android is now supported in release 5.  These APIs are still missing, but the new page action is a reasonable way of adding rules.
